from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence


EXPECTED_CASE_COUNT = 25
EXPECTED_GROUP_COUNTS = {
    "api_sse": 2,
    "regression": 6,
    "taxonomy": 11,
    "logistics": 4,
    "ui": 2,
}

EXPECTED_TAXONOMY_LABELS = {
    "Accessories",
    "T-Shirts",
    "Mugs",
    "Tank Tops",
    "Hoodies",
    "Sweatshirts",
    "Ornaments & Gifts",
    "Home Decor & Flags",
    "Sportswear",
    "Blankets",
    "Bottoms & Shorts",
    "Baby & Kids",
    "Pajamas & Sleepwear",
    "Polo Shirts",
}

ACCESSORY_SUBTYPE_LABELS = {
    "canvas_ambiguity",
    "hats",
    "ornaments",
    "drinkware",
    "home_goods",
    "keychain",
    "tote_bag",
    "acrylic_gift",
    "desk_utility",
    "pillow",
    "socks",
    "sticker",
    "poster",
    "textile_art",
    "classic_cap",
    "dad_hat",
    "trucker_hat",
    "bucket_hat",
    "glass_ornament",
    "wood_ornament",
    "aluminum_ornament",
    "long_sleeve",
    "bottle",
    "tritan_cup",
    "wall_clock",
    "towel",
    "tapestry",
    "candle_holder",
    "wallet_insert",
    "plaque",
    "acrylic_block",
    "sneaker",
    "canvas_shoes",
    "youth_baseball_jersey",
    "phone_grip",
    "phone_charm",
    "suncatcher",
}


@dataclass(frozen=True)
class E2ECase:
    case_id: str
    priority: str
    group: str
    turns: Sequence[str]
    min_items: int = 0
    max_items: Optional[int] = None
    allowed_categories: Sequence[str] = field(default_factory=tuple)
    forbidden_terms: Sequence[str] = field(default_factory=tuple)
    required_terms: Sequence[str] = field(default_factory=tuple)
    required_any_terms: Sequence[str] = field(default_factory=tuple)
    required_turn_any_terms: Sequence[Sequence[str]] = field(default_factory=tuple)
    required_color: Optional[str] = None
    required_size: Optional[str] = None
    max_base_cost: Optional[float] = None
    min_base_cost: Optional[float] = None
    require_final_payload: bool = True
    require_graceful_empty: bool = True
    require_clarification: bool = False
    require_margin_alert: bool = False
    require_zone_mapping: bool = False
    require_carrier_partner: bool = False
    require_cheapest_shipping: bool = False
    require_shipping_formula: bool = False
    require_delivery_time: bool = False
    require_partner_fallback: bool = False
    expected_missing_field: Optional[str] = None
    expected_quantity: Optional[int] = None
    max_delivery_days: Optional[int] = None
    expected_country_terms: Sequence[str] = field(default_factory=tuple)
    expected_carrier_terms: Sequence[str] = field(default_factory=tuple)
    ui_viewports: Sequence[Dict[str, int]] = field(default_factory=tuple)
    taxonomy_label: Optional[str] = None
    accessory_subtype_label: Optional[str] = None
    notes: str = ""


VIEWPORTS = (
    {"width": 1440, "height": 1000},
    {"width": 1024, "height": 900},
    {"width": 390, "height": 844},
)


CASES: List[E2ECase] = [
    E2ECase(
        case_id="API-01",
        priority="P0",
        group="api_sse",
        turns=("Heavy cotton t-shirt ship to US",),
        min_items=1,
        allowed_categories=("T-Shirts",),
        required_any_terms=("heavy cotton", "t-shirt", "tee", "gildan"),
        forbidden_terms=("hoodie", "sweatshirt", "mug", "tank top"),
        taxonomy_label="T-Shirts",
    ),
    E2ECase(
        case_id="API-02",
        priority="P0",
        group="api_sse",
        turns=("ngoài áo thun ship US ra thì còn những sản phẩm nào nữa tôi muốn tìm nhiều loại khác nhau",),
        require_graceful_empty=True,
        notes="Regression for IncompleteRead/NoneType failure in old E2E log.",
    ),
    E2ECase(
        case_id="API-03",
        priority="P1",
        group="api_sse",
        turns=("Antarctica mug delivery with invalid postal 000000",),
        require_graceful_empty=True,
        taxonomy_label="Mugs",
    ),
    E2ECase(
        case_id="REG-01",
        priority="P0",
        group="regression",
        turns=("Recommend Unisex Crewneck Sweatshirt Comfort Colors 1566 ship to US", "nó có loại rẻ hơn không?"),
        min_items=1,
        allowed_categories=("Sweatshirts",),
        required_any_terms=("sweatshirt", "crewneck", "USCC1566", "Comfort Colors 1566"),
        forbidden_terms=("hoodie", "mug", "tank top"),
        taxonomy_label="Sweatshirts",
    ),
    E2ECase(
        case_id="REG-02",
        priority="P0",
        group="regression",
        turns=("AOP Sports Bra VN", "cái đó ship VN được không?"),
        require_graceful_empty=True,
        required_any_terms=("sports bra", "bra", "VNB3DSB"),
        taxonomy_label="Sportswear",
    ),
    E2ECase(
        case_id="REG-03",
        priority="P0",
        group="regression",
        turns=("AOP Unisex Hawaiian Shirt VN ship to US", "cái này có size nào?"),
        require_graceful_empty=True,
        required_any_terms=("hawaiian", "shirt", "VNB3DUH"),
        forbidden_terms=("mug", "ceramic", "hoodie"),
        taxonomy_label="T-Shirts",
    ),
    E2ECase(
        case_id="REG-04",
        priority="P0",
        group="regression",
        turns=("AOP Men's Tank Top ship to US", "mẫu đó màu black size M có không?"),
        require_graceful_empty=True,
        allowed_categories=("Tank Tops",),
        required_any_terms=("tank", "EUAPMTT"),
        required_color="Black",
        required_size="M",
        forbidden_terms=("hoodie", "mug"),
        taxonomy_label="Tank Tops",
    ),
    E2ECase(
        case_id="REG-05",
        priority="P0",
        group="regression",
        turns=("Find USMG18500 Classic Unisex Hoodie Gildan 18500 ship to US",),
        min_items=1,
        allowed_categories=("Hoodies",),
        required_any_terms=("USMG18500", "Gildan 18500", "hoodie"),
        forbidden_terms=("sweatshirt", "mug", "tank top"),
        taxonomy_label="Hoodies",
    ),
    E2ECase(
        case_id="REG-06",
        priority="P0",
        group="regression",
        turns=("Find US3DAM15 3D Accent Mug 15oz US",),
        require_graceful_empty=True,
        allowed_categories=("Mugs",),
        required_any_terms=("US3DAM15", "mug", "15oz"),
        forbidden_terms=("hoodie", "t-shirt", "tank top"),
        taxonomy_label="Mugs",
    ),
    E2ECase(
        case_id="REG-07",
        priority="P1",
        group="regression",
        turns=("Find ACC30TGM Tumbler 30oz Half Print ship to US",),
        require_graceful_empty=True,
        allowed_categories=("Accessories",),
        required_any_terms=("ACC30TGM", "tumbler", "30oz"),
        forbidden_terms=("hoodie", "t-shirt", "11oz"),
        taxonomy_label="Accessories",
        accessory_subtype_label="drinkware",
    ),
    E2ECase(
        case_id="REG-08",
        priority="P0",
        group="regression",
        turns=("Tìm các mẫu Hoodie có biên lợi nhuận (Gross Margin) >= 50% nếu tôi bán với giá $25 và ship nội địa Mỹ.",),
        require_graceful_empty=True,
        require_margin_alert=True,
        required_any_terms=("hoodie", "margin", "biên lợi nhuận", "50", "25"),
        taxonomy_label="Hoodies",
        notes="Margin % = ((Selling Price - Total Cost) / Selling Price) * 100; hoodie min base cost 12.5 plus US shipping cannot safely hit 50% at $25.",
    ),
    E2ECase(
        case_id="REG-09",
        priority="P0",
        group="regression",
        turns=("Xưởng nào ship T-Shirt nội địa US nhanh nhất với giá cạnh tranh?", "Đặt giá bán lẻ là $25"),
        min_items=3,
        allowed_categories=("T-Shirts",),
        required_any_terms=("T-Shirt", "margin", "profit", "25"),
        forbidden_terms=("tote", "keychain", "mug", "hoodie"),
        taxonomy_label="T-Shirts",
        notes="Retail price override must apply margin metadata across the active T-Shirt comparison matrix instead of collapsing to one selected SKU.",
    ),
    E2ECase(
        case_id="TAX-01",
        priority="P0",
        group="taxonomy",
        turns=("Canvas style",),
        max_items=0,
        require_clarification=True,
        required_any_terms=("canvas", "clarify", "tranh", "giày", "wall art", "shoes"),
        taxonomy_label="Accessories",
        accessory_subtype_label="canvas_ambiguity",
        notes="Keyword overlap trap: Canvas Print vs Canvas Shoes must ask clarification instead of returning arbitrary product.",
    ),
    E2ECase(
        case_id="TAX-02",
        priority="P0",
        group="taxonomy",
        turns=("Recommend acrylic ornament for Christmas ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_any_terms=("acrylic ornament", "ornament", "christmas"),
        forbidden_terms=("hoodie", "t-shirt", "mug"),
        taxonomy_label="Ornaments & Gifts",
        accessory_subtype_label="ornaments",
    ),
    E2ECase(
        case_id="TAX-03",
        priority="P0",
        group="taxonomy",
        turns=("Recommend doormat for home entry ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_any_terms=("doormat", "home", "entry"),
        forbidden_terms=("blanket", "t-shirt", "hoodie"),
        taxonomy_label="Home Decor & Flags",
        accessory_subtype_label="home_goods",
    ),
    E2ECase(
        case_id="TAX-04",
        priority="P1",
        group="taxonomy",
        turns=("Recommend keychain gift ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_any_terms=("keychain", "key chain"),
        forbidden_terms=("hoodie", "t-shirt", "mug"),
        taxonomy_label="Accessories",
        accessory_subtype_label="keychain",
    ),
    E2ECase(
        case_id="TAX-05",
        priority="P1",
        group="taxonomy",
        turns=("Recommend tote bag ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_any_terms=("tote", "bag"),
        forbidden_terms=("hoodie", "sweatshirt", "mug"),
        taxonomy_label="Accessories",
        accessory_subtype_label="tote_bag",
    ),
    E2ECase(
        case_id="TAX-06",
        priority="P1",
        group="taxonomy",
        turns=("Recommend acrylic night light gift ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_any_terms=("night light", "acrylic", "plaque", "block"),
        forbidden_terms=("tumbler", "mug", "hoodie"),
        taxonomy_label="Ornaments & Gifts",
        accessory_subtype_label="acrylic_gift",
    ),
    E2ECase(
        case_id="TAX-07",
        priority="P1",
        group="taxonomy",
        turns=("Recommend mouse pad for desk ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_any_terms=("mouse pad", "desk"),
        forbidden_terms=("hoodie", "mug", "t-shirt"),
        taxonomy_label="Accessories",
        accessory_subtype_label="desk_utility",
    ),
    E2ECase(
        case_id="TAX-08",
        priority="P0",
        group="taxonomy",
        turns=("Recommend garden flag for yard ship to US",),
        min_items=1,
        required_any_terms=("garden flag", "house flag", "flag"),
        forbidden_terms=("hoodie", "t-shirt", "mug"),
        taxonomy_label="Home Decor & Flags",
    ),
    E2ECase(
        case_id="TAX-09",
        priority="P0",
        group="taxonomy",
        turns=("Recommend sherpa blanket ship to US",),
        min_items=1,
        required_any_terms=("sherpa", "fleece", "minky", "blanket"),
        forbidden_terms=("towel", "tapestry", "hoodie", "t-shirt"),
        taxonomy_label="Blankets",
    ),
    E2ECase(
        case_id="TAX-10",
        priority="P0",
        group="taxonomy",
        turns=("Recommend AOP basketball shorts ship to US",),
        min_items=1,
        required_any_terms=("basketball shorts", "shorts", "sweatpant"),
        forbidden_terms=("t-shirt", "hoodie", "mug"),
        taxonomy_label="Bottoms & Shorts",
    ),
    E2ECase(
        case_id="TAX-11",
        priority="P0",
        group="taxonomy",
        turns=("Recommend baby onesie ship to US",),
        min_items=1,
        required_any_terms=("baby", "onesie", "toddler", "kid"),
        forbidden_terms=("adult only", "mug", "blanket"),
        taxonomy_label="Baby & Kids",
    ),
    E2ECase(
        case_id="TAX-12",
        priority="P1",
        group="taxonomy",
        turns=("Recommend satin pajama set ship to US",),
        min_items=1,
        required_any_terms=("pajama", "sleepwear", "satin"),
        forbidden_terms=("hoodie", "t-shirt", "mug"),
        taxonomy_label="Pajamas & Sleepwear",
    ),
    E2ECase(
        case_id="TAX-13",
        priority="P0",
        group="taxonomy",
        turns=("quần pijama thì có những sản phẩm nào ship to US", "tôi hỏi quần ngủ cơ mà"),
        min_items=1,
        required_any_terms=("pajama", "sleepwear", "satin"),
        forbidden_terms=("hawaiian shorts", "basketball shorts", "leggings", "sweatpant"),
        taxonomy_label="Pajamas & Sleepwear",
        notes="Regression for Vietnamese pajama subtype overriding broad Bottoms & Shorts context without stale item bleed.",
    ),
    E2ECase(
        case_id="TAX-14",
        priority="P0",
        group="taxonomy",
        turns=("có sản phẩm tất nào không ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_terms=("Crew Socks",),
        forbidden_terms=("sticker", "tote", "keychain", "mug", "hat", "cap", "doormat", "poster", "canvas", "ornament", "tumbler", "bottle", "clock", "towel", "tapestry", "pillow", "wallet", "plaque", "sneaker", "shoe", "mouse pad", "phone grip", "phone charm", "suncatcher"),
        require_graceful_empty=False,
        taxonomy_label="Accessories",
        accessory_subtype_label="socks",
        notes="Accessories leaf-node isolation: Vietnamese socks must return Crew Socks only, not generic accessories or empty fallback.",
    ),
    E2ECase(
        case_id="TAX-15",
        priority="P0",
        group="taxonomy",
        turns=("tìm mẫu mũ nón ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_terms=("Classic Cap",),
        forbidden_terms=("dad hat", "trucker", "bucket", "sticker", "tote", "keychain", "mug", "sock", "doormat", "poster", "canvas", "ornament", "tumbler", "bottle", "clock", "towel", "tapestry", "pillow", "wallet", "plaque", "sneaker", "shoe", "mouse pad", "phone grip", "phone charm", "suncatcher"),
        require_graceful_empty=False,
        taxonomy_label="Accessories",
        accessory_subtype_label="classic_cap",
        notes="Accessories leaf-node isolation: Vietnamese headwear query must resolve to Classic Cap only, not broad hat variants.",
    ),
    E2ECase(
        case_id="TAX-16",
        priority="P0",
        group="taxonomy",
        turns=("muốn mua thảm chùi chân ship to US",),
        min_items=1,
        required_terms=("Doormat",),
        forbidden_terms=("sticker", "tote", "keychain", "mug", "sock", "hat", "cap", "poster", "canvas", "ornament", "tumbler", "bottle", "clock", "towel", "tapestry", "pillow", "wallet", "plaque", "sneaker", "shoe", "mouse pad", "phone grip", "phone charm", "suncatcher"),
        require_graceful_empty=False,
        taxonomy_label="Home Decor & Flags",
        accessory_subtype_label="home_goods",
        notes="Accessories leaf-node isolation: doormat query must return Doormat only, not other Accessories items.",
    ),
    E2ECase(
        case_id="TAX-17",
        priority="P0",
        group="taxonomy",
        turns=("gợi ý mẫu sticker ship to US",),
        min_items=1,
        allowed_categories=("Accessories",),
        required_terms=("Sticker",),
        forbidden_terms=("tote", "keychain", "mug", "sock", "hat", "cap", "doormat", "poster", "canvas", "ornament", "tumbler", "bottle", "clock", "towel", "tapestry", "pillow", "wallet", "plaque", "sneaker", "shoe", "mouse pad", "phone grip", "phone charm", "suncatcher"),
        require_graceful_empty=False,
        taxonomy_label="Accessories",
        accessory_subtype_label="sticker",
        notes="Accessories leaf-node isolation: sticker query must return Sticker only, not other Accessories items.",
    ),
    E2ECase(case_id="TAX-18", priority="P0", group="taxonomy", turns=("Recommend canvas print wall decor ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("canvas print", "framed canvas"), forbidden_terms=("poster", "textile art", "t-shirt", "tank top"), taxonomy_label="Accessories", accessory_subtype_label="canvas_ambiguity"),
    E2ECase(case_id="TAX-19", priority="P0", group="taxonomy", turns=("Recommend poster wall decor ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("poster",), forbidden_terms=("canvas", "textile art", "tote", "keychain"), taxonomy_label="Accessories", accessory_subtype_label="poster"),
    E2ECase(case_id="TAX-20", priority="P0", group="taxonomy", turns=("Recommend textile art wall decor ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("textile art",), forbidden_terms=("poster", "canvas", "tote", "keychain"), taxonomy_label="Accessories", accessory_subtype_label="textile_art"),
    E2ECase(case_id="TAX-21", priority="P0", group="taxonomy", turns=("Recommend classic cap ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("classic cap",), forbidden_terms=("dad hat", "trucker", "bucket", "sticker", "tote"), taxonomy_label="Accessories", accessory_subtype_label="classic_cap"),
    E2ECase(case_id="TAX-22", priority="P0", group="taxonomy", turns=("Recommend dad hat ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("dad hat", "dad cap"), forbidden_terms=("classic cap", "trucker", "bucket", "sticker", "tote"), taxonomy_label="Accessories", accessory_subtype_label="dad_hat"),
    E2ECase(case_id="TAX-23", priority="P0", group="taxonomy", turns=("Recommend trucker hat ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("trucker hat",), forbidden_terms=("classic cap", "dad hat", "bucket", "sticker", "tote"), taxonomy_label="Accessories", accessory_subtype_label="trucker_hat"),
    E2ECase(case_id="TAX-24", priority="P0", group="taxonomy", turns=("Recommend bucket hat ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("bucket hat",), forbidden_terms=("classic cap", "dad hat", "trucker", "sticker", "tote"), taxonomy_label="Accessories", accessory_subtype_label="bucket_hat"),
    E2ECase(case_id="TAX-25", priority="P0", group="taxonomy", turns=("Recommend glass ornament ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("glass ornament",), forbidden_terms=("acrylic ornament", "aluminum ornament", "keychain", "tote"), taxonomy_label="Accessories", accessory_subtype_label="glass_ornament"),
    E2ECase(case_id="TAX-26", priority="P0", group="taxonomy", turns=("Recommend aluminum ornament ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("aluminum ornament", "aluminium ornament"), forbidden_terms=("acrylic ornament", "glass ornament", "keychain", "tote"), taxonomy_label="Accessories", accessory_subtype_label="aluminum_ornament"),
    E2ECase(case_id="TAX-27", priority="P0", group="taxonomy", turns=("Recommend wood ornament ship to US",), max_items=0, required_any_terms=("không tìm thấy", "no matching", "no matching products", "không có"), forbidden_terms=("acrylic ornament", "glass ornament", "aluminum ornament", "keychain", "tote"), taxonomy_label="Accessories", accessory_subtype_label="wood_ornament"),
    E2ECase(case_id="TAX-28", priority="P0", group="taxonomy", turns=("Recommend unisex long sleeve ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("long sleeve",), forbidden_terms=("t-shirt", "hoodie", "sweatshirt", "tank top", "polo"), taxonomy_label="Accessories", accessory_subtype_label="long_sleeve"),
    E2ECase(case_id="TAX-29", priority="P0", group="taxonomy", turns=("Recommend stainless steel bottle ship to US",), min_items=1, required_any_terms=("bottle", "stainless steel bottle"), forbidden_terms=("tumbler", "tritan cup", "mug", "sticker"), taxonomy_label="Accessories", accessory_subtype_label="bottle"),
    E2ECase(case_id="TAX-30", priority="P0", group="taxonomy", turns=("Recommend Tritan Cup ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("tritan cup",), forbidden_terms=("bottle", "tumbler", "mug", "sticker"), taxonomy_label="Accessories", accessory_subtype_label="tritan_cup"),
    E2ECase(case_id="TAX-31", priority="P0", group="taxonomy", turns=("Recommend wall clock ship to UK",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("clock", "wall clock"), forbidden_terms=("towel", "tapestry", "pillow", "doormat"), taxonomy_label="Accessories", accessory_subtype_label="wall_clock"),
    E2ECase(case_id="TAX-32", priority="P0", group="taxonomy", turns=("Recommend towel ship to UK",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("towel",), forbidden_terms=("clock", "tapestry", "pillow", "doormat"), taxonomy_label="Accessories", accessory_subtype_label="towel"),
    E2ECase(case_id="TAX-33", priority="P0", group="taxonomy", turns=("Recommend tapestry ship to UK",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("tapestry",), forbidden_terms=("clock", "towel", "pillow", "doormat"), taxonomy_label="Accessories", accessory_subtype_label="tapestry"),
    E2ECase(case_id="TAX-34", priority="P0", group="taxonomy", turns=("Recommend candle holder gift ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("candle holder",), forbidden_terms=("night light", "plaque", "ornament", "keychain"), taxonomy_label="Accessories", accessory_subtype_label="candle_holder"),
    E2ECase(case_id="TAX-35", priority="P0", group="taxonomy", turns=("Recommend wallet insert card ship to VN",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("wallet insert", "wallet insert card"), forbidden_terms=("keychain", "tote", "sticker", "phone charm"), taxonomy_label="Accessories", accessory_subtype_label="wallet_insert"),
    E2ECase(case_id="TAX-36", priority="P0", group="taxonomy", turns=("Recommend acrylic plaque ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("plaque",), forbidden_terms=("night light", "acrylic block", "ornament", "keychain"), taxonomy_label="Accessories", accessory_subtype_label="plaque"),
    E2ECase(case_id="TAX-37", priority="P0", group="taxonomy", turns=("Recommend acrylic block ship to VN",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("acrylic block",), forbidden_terms=("night light", "plaque", "ornament", "keychain"), taxonomy_label="Accessories", accessory_subtype_label="acrylic_block"),
    E2ECase(case_id="TAX-38", priority="P0", group="taxonomy", turns=("Recommend sneaker ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("sneaker",), forbidden_terms=("canvas shoes", "sock", "tote", "keychain"), taxonomy_label="Accessories", accessory_subtype_label="sneaker"),
    E2ECase(case_id="TAX-39", priority="P0", group="taxonomy", turns=("Recommend canvas shoes ship to US",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("canvas shoes",), forbidden_terms=("canvas print", "poster", "sock", "sneaker"), taxonomy_label="Accessories", accessory_subtype_label="canvas_shoes"),
    E2ECase(case_id="TAX-40", priority="P0", group="taxonomy", turns=("Recommend youth baseball jersey ship to VN",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("baseball jersey", "youth"), forbidden_terms=("onesie", "t-shirt", "hoodie", "sticker"), taxonomy_label="Accessories", accessory_subtype_label="youth_baseball_jersey"),
    E2ECase(case_id="TAX-41", priority="P0", group="taxonomy", turns=("Recommend phone grip ship to VN",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("phone grip",), forbidden_terms=("phone charm", "sticker", "keychain", "mouse pad"), taxonomy_label="Accessories", accessory_subtype_label="phone_grip"),
    E2ECase(case_id="TAX-42", priority="P0", group="taxonomy", turns=("Recommend phone charm ship to VN",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("phone charm",), forbidden_terms=("phone grip", "sticker", "keychain", "mouse pad"), taxonomy_label="Accessories", accessory_subtype_label="phone_charm"),
    E2ECase(case_id="TAX-43", priority="P0", group="taxonomy", turns=("Recommend suncatcher ship to VN",), min_items=1, allowed_categories=("Accessories",), required_any_terms=("suncatcher",), forbidden_terms=("sticker", "keychain", "mouse pad", "phone charm"), taxonomy_label="Accessories", accessory_subtype_label="suncatcher"),
    E2ECase(
        case_id="LOG-01",
        priority="P0",
        group="logistics",
        turns=("Recommend USG5000 T-Shirt ship to US", "If I change the destination to Germany (DE), what is the shipping fee?"),
        min_items=1,
        require_zone_mapping=True,
        require_carrier_partner=True,
        require_cheapest_shipping=True,
        require_partner_fallback=True,
        expected_country_terms=("US", "DE", "Germany", "zone_id"),
        expected_carrier_terms=("USPS", "DHL", "Asendia", "DPD", "LaPoste", "Yunexpress", "Standard Shipping"),
        taxonomy_label="T-Shirts",
    ),
    E2ECase(
        case_id="LOG-02",
        priority="P0",
        group="logistics",
        turns=("I want to buy 5 pcs of US3DAM15 (3D Accent Mug) sent to California, USA. Calculate the total shipping cost.",),
        min_items=1,
        require_graceful_empty=False,
        require_zone_mapping=True,
        require_carrier_partner=True,
        require_shipping_formula=True,
        expected_quantity=5,
        expected_country_terms=("US", "USA", "California", "zone_id"),
        expected_carrier_terms=("USPS", "DHL", "UPS", "OnTrac", "Standard Shipping"),
        taxonomy_label="Mugs",
    ),
    E2ECase(
        case_id="LOG-03",
        priority="P1",
        group="logistics",
        turns=("Mẫu áo polo VNB3DPMP sản xuất ở xưởng KingPrint VN hay Truong Son có ship được sang Anh (UK) không và đi bằng hãng nào?",),
        min_items=1,
        require_zone_mapping=True,
        require_carrier_partner=True,
        require_partner_fallback=True,
        expected_country_terms=("UK", "GB", "United Kingdom", "zone_id"),
        expected_carrier_terms=("Evri", "Royal Mail", "DHL", "Yunexpress", "Asendia", "USPS"),
        required_any_terms=("VNB3DPMP", "polo", "Truong Son", "KingPrint"),
        taxonomy_label="Polo Shirts",
    ),
    E2ECase(
        case_id="LOG-04",
        priority="P1",
        group="logistics",
        turns=("Tìm mẫu mũ dad hat style ship to US", "Tôi muốn mua thêm tranh canvas style ship to US"),
        min_items=1,
        required_turn_any_terms=(("dad hat", "cap", "hat"), ("canvas", "wall art", "poster", "tranh")),
        allowed_categories=("Accessories",),
        taxonomy_label="Accessories",
        accessory_subtype_label="hats",
    ),
    E2ECase(
        case_id="LOG-05",
        priority="P1",
        group="logistics",
        turns=("Tôi muốn đặt 1 chiếc áo Unisex T-Shirt Gildan 5000 ship đến Đức để tặng sinh nhật vào đúng 4 ngày nữa, xưởng nào đáp ứng được?",),
        require_zone_mapping=True,
        require_delivery_time=True,
        require_clarification=True,
        max_delivery_days=4,
        expected_country_terms=("DE", "Germany", "Đức", "zone_id"),
        required_any_terms=("delivery_time", "4 ngày", "trễ", "không đáp ứng", "rủi ro", "5-10", "4-6"),
        taxonomy_label="T-Shirts",
    ),
    E2ECase(
        case_id="LOG-06",
        priority="P0",
        group="logistics",
        turns=("Tôi muốn mua áo T-Shirt",),
        max_items=0,
        require_clarification=True,
        expected_missing_field="shipping_location",
        required_any_terms=("hỗ trợ giao đến", "US", "VN", "shipping_location"),
        taxonomy_label="T-Shirts",
        notes="Missing destination must ask for shipping_location instead of defaulting to US shipping fees.",
    ),
    E2ECase(
        case_id="LOG-07",
        priority="P0",
        group="logistics",
        turns=("tôi muốn mua mũ đội", "AU"),
        min_items=1,
        required_any_terms=("hat", "cap"),
        forbidden_terms=("keychain", "tank top", "t-shirt", "jersey", "mug", "poster", "landscape"),
        notes="Country clarification suggestions must intersect valid hat/cap variants with first_item_fee > 0 routes, and choosing a suggested country must return matching hat/cap items.",
    ),
    E2ECase(
        case_id="LOG-08",
        priority="P0",
        group="logistics",
        turns=("đồ ngủ ship VN", "vậy thì thị trường nào có đồ ngủ"),
        max_items=0,
        required_terms=("Pajamas & Sleepwear",),
        required_any_terms=("US", "DE", "VN"),
        forbidden_terms=("tank top", "jersey", "mug", "poster"),
        taxonomy_label="Pajamas & Sleepwear",
        notes="Global market availability questions must clear sticky country slots and return product-specific countries without stale localized catalog cards.",
    ),
    E2ECase(
        case_id="UI-01",
        priority="P0",
        group="ui",
        turns=("Heavy cotton t-shirt ship to US",),
        min_items=1,
        allowed_categories=("T-Shirts",),
        ui_viewports=({"width": 1440, "height": 1000},),
        taxonomy_label="T-Shirts",
    ),
    E2ECase(
        case_id="UI-02",
        priority="P0",
        group="ui",
        turns=("Pillow for US market",),
        min_items=1,
        required_any_terms=("pillow",),
        ui_viewports=VIEWPORTS,
        taxonomy_label="Accessories",
        accessory_subtype_label="pillow",
    ),
]

DEFAULT_ACTIVE_CASE_IDS = (
    "API-01",
    "API-02",
    "REG-01",
    "REG-02",
    "REG-03",
    "REG-04",
    "REG-08",
    "REG-09",
    "TAX-01",
    "TAX-08",
    "TAX-13",
    "TAX-14",
    "TAX-15",
    "TAX-16",
    "TAX-17",
    "TAX-21",
    "TAX-22",
    "TAX-23",
    "TAX-24",
    "LOG-01",
    "LOG-06",
    "LOG-07",
    "LOG-08",
    "UI-01",
    "UI-02",
)

_CASES_BY_ID = {case.case_id: case for case in CASES}
_MISSING_ACTIVE_CASE_IDS = [case_id for case_id in DEFAULT_ACTIVE_CASE_IDS if case_id not in _CASES_BY_ID]
if _MISSING_ACTIVE_CASE_IDS:
    raise RuntimeError(f"Missing active E2E case IDs: {_MISSING_ACTIVE_CASE_IDS}")

CASES = [_CASES_BY_ID[case_id] for case_id in DEFAULT_ACTIVE_CASE_IDS]
CASE_IDS = [case.case_id for case in CASES]

if len(CASES) != EXPECTED_CASE_COUNT:
    raise RuntimeError(f"Expected {EXPECTED_CASE_COUNT} E2E cases, got {len(CASES)}")

if len(CASE_IDS) != len(set(CASE_IDS)):
    duplicates = sorted({case_id for case_id in CASE_IDS if CASE_IDS.count(case_id) > 1})
    raise RuntimeError(f"Duplicate E2E case IDs: {duplicates}")
